// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUbLRKGJ6wZRVhFBZ-1iSQVCs4yaNOlI',
    appId: '1:782571979521:web:1ce06dce1de6baccad9100',
    messagingSenderId: '782571979521',
    projectId: 'budget-loft',
    authDomain: 'budget-loft.firebaseapp.com',
    storageBucket: 'budget-loft.firebasestorage.app',
    measurementId: 'G-YPETRV5S1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Sq2VAj1--VCzw5oHkapr5cLMfwjePVs',
    appId: '1:782571979521:android:0b8f6cb3d9632f13ad9100',
    messagingSenderId: '782571979521',
    projectId: 'budget-loft',
    storageBucket: 'budget-loft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJpTnNo_kXYaGMHd_M3aBDeU5xSk_Qy4',
    appId: '1:782571979521:ios:538888a5e33d16d1ad9100',
    messagingSenderId: '782571979521',
    projectId: 'budget-loft',
    storageBucket: 'budget-loft.firebasestorage.app',
    iosBundleId: 'com.example.budgetloft4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJpTnNo_kXYaGMHd_M3aBDeU5xSk_Qy4',
    appId: '1:782571979521:ios:2b33063ce47c3cd8ad9100',
    messagingSenderId: '782571979521',
    projectId: 'budget-loft',
    storageBucket: 'budget-loft.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFUbLRKGJ6wZRVhFBZ-1iSQVCs4yaNOlI',
    appId: '1:782571979521:web:cf07c0465c2ac80ead9100',
    messagingSenderId: '782571979521',
    projectId: 'budget-loft',
    authDomain: 'budget-loft.firebaseapp.com',
    storageBucket: 'budget-loft.firebasestorage.app',
    measurementId: 'G-YCK0R3HRHC',
  );

}